language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install setuptools>=26.0
  - pip install pytest==3.0.6
  - pip install coveralls pytest-cov pytest-warnings==0.2.0
  - pip install https://github.com/darcymason/pydicom/archive/master.zip
  - pip install .
# command to run tests
script: py.test -W ignore --cov .
after_success:
  - coveralls
deploy:
  provider: pypi
  user: bennyrowland
  password:
    secure: auQPAii17z1RxDveUr1sZmxu69kHXEOjet6wBDTZR5EUaSNKH9enIAZtWc5E9G5DNEXRCYcwZE+Tmq6R2VefQtw3+t/fWPMguBc44Q8InsjVtUqyZGjTJmjkaoNUh/Ago2WgW9ifMDinSpZegjyj8cKojw8iGDtgytXeAz02bf4vLetxPn3unpR0mTkJLr128TKFlNzuv26zv0idvhPTG+gw41zleGugi1ekE1lt1dbb7DTuH0yvQtgIXNBB4l4Rwhnq+10h6cEEvHTDz4YR84Q8LUT3DUeP7gx0ZObPRpuHH9QXF0jLlg6o1wjrf7Gcgn4Lrsx9Sb1ApNLG3Rd5P50X9Z4CnAF3c0NRBz3qgF0TFO34j86XYP9zkSYjS0N2QndCb1uMe/OyMX3UkHZ2ygYTSRJaulkjrFlbc6MjzwO8MZS+WCcAlyKsEiuYluUB7OqdcUSDhscvtVfMh9ijSj+G2dbCoreqUzkD9zGqOZKFFXNWHrzVPznxKqD1+RCPQFbasiRfqlqR5HVj1ZW3pXIqRr6E3LpM9AwH3xiOQn6IYO9NKKOvc9XCy7qI3dWyePgYxElrEQ7xpiS890dMHOROAOrZElAgznEfyBfRGq5gQlTf0/bbpM0OCnAC/dewVnLObYhDdUF4kE+F0ofo7+zpdtZy8RDWEazDwXlD0k0=
  distributions: "sdist bdist_wheel"